require:
  - rubocop-rake
  - rubocop-rspec
AllCops:
  Exclude:
    - 'Gemfile'
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Layout/LineLength:
  Exclude:
    - 'spec/**/*'
    